# Generated by Django 5.1.2 on 2024-11-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_submission_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(upload_to='media/')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collections', to='users.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collections', to='project.researchproject')),
            ],
        ),
    ]
